AWSTemplateFormatVersion: "2010-09-09"
Description: Megatron Sample Template
Resources:
  EC2DevelopmentInstance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-03368e982f317ae48" #Amazon Linux 2 AMI - US East 1
      InstanceType: t2.micro
      KeyName: megatron
      SecurityGroups: ["Megatron"]
      UserData: {{.UserData}}
      # For now, use the default block device mapping
      # BlockDeviceMappings:
      #   -
      #     DeviceName: /dev/xvda
      #     Ebs:
      #       VolumeType: io1
      #       Iops: 200
      #       DeleteOnTermination: false
      #       VolumeSize: 20