---
- name: Setup docker on megatron
  hosts: localhost
  tasks:

    - name: Install docker
      ansible.builtin.package:
        name:
          - docker
        state: latest
      become: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      become: yes